
name: 'taxi'
version: '1.0.0'
profile: 'taxi'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  taxi:
    staging:
      +materialized: view
      +schema: silver
      tags: [silver, staging]
    preparation:
      +materialized: table
      +schema: silver
      tags: [silver, prep]
    base:
      +materialized: table
      +schema: silver
      tags: [silver, base]
    mart:
      +materialized: table
      +schema: gold
      tags: [gold, mart]
seeds:
  taxi:
    +enabled: true
    +schema: bronze

    taxi_zone_lookup:
      description: >
        Taxi zone lookup data with coordinates from the NYC TLC.
    
    weather_code_mapping:
      description: >
        Weather code mapping to the weather code description.